# Generated by Django 4.2.3 on 2023-08-18 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_event_endtime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('pastor', 'Pastor'), ('elder', 'Elder'), ('other', 'Other Leader')], max_length=10)),
                ('image', models.ImageField(upload_to='static/leader')),
            ],
        ),
    ]
