# Generated by Django 4.2.3 on 2023-08-20 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_contact_gallary_ministry_alter_blog_host_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leader',
            name='category',
            field=models.CharField(choices=[('Pastors', 'Pastors'), ('Elder', 'Elder'), ('Other Church Leaders', 'Other Leader')], max_length=50),
        ),
    ]
