# Generated by Django 4.2.3 on 2023-08-20 08:31

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_sons'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videolink', embed_video.fields.EmbedVideoField(default='https://www.youtube.com/embed/XFrjmhTyiYI')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-updated', '-created'],
            },
        ),
        migrations.RenameModel(
            old_name='Sons',
            new_name='Live',
        ),
    ]
