# Generated by Django 4.2.3 on 2023-08-20 08:36

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_rename_live_livestream'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livestream',
            name='videolink',
            field=embed_video.fields.EmbedVideoField(),
        ),
        migrations.AlterField(
            model_name='sermon',
            name='videolink',
            field=embed_video.fields.EmbedVideoField(),
        ),
        migrations.AlterField(
            model_name='song',
            name='videolink',
            field=embed_video.fields.EmbedVideoField(),
        ),
    ]
