# Generated by Django 4.2.3 on 2023-08-27 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('subtitle', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(null=True, upload_to='static/carousel')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-updated', '-created'],
            },
        ),
    ]
