# Generated by Django 4.2.3 on 2023-08-27 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_alter_carousel_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='topic',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
    ]
