# Generated by Django 4.2.3 on 2023-08-27 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_event_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='activity',
            field=models.CharField(db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='gallery',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='gallery',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.ministry'),
        ),
        migrations.AddField(
            model_name='sermon',
            name='activity',
            field=models.CharField(db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sermon',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='sermon',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.ministry'),
        ),
        migrations.AddField(
            model_name='song',
            name='activity',
            field=models.CharField(db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.ministry'),
        ),
    ]
