# Generated by Django 4.2.3 on 2023-08-27 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_gallery_activity_gallery_date_gallery_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sermon',
            name='activity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.event'),
        ),
        migrations.AlterField(
            model_name='song',
            name='activity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.event'),
        ),
    ]
