# Generated by Django 4.2.3 on 2023-08-27 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_alter_sermon_activity_alter_song_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='activity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.event'),
        ),
    ]
