# Generated by Django 4.2.3 on 2023-08-27 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_alter_gallery_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.event'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.ministry'),
        ),
        migrations.AlterField(
            model_name='sermon',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.event'),
        ),
        migrations.AlterField(
            model_name='sermon',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.ministry'),
        ),
        migrations.AlterField(
            model_name='song',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.event'),
        ),
        migrations.AlterField(
            model_name='song',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.ministry'),
        ),
    ]
